name: Upload Riddle Short (daily)

on:
  schedule:
    - cron: '0 10 * * *'   # runs daily at 10:00 UTC — adjust as needed
  workflow_dispatch:        # manual trigger

permissions:
  contents: write   # needed to commit changes back

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with write permissions)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg and system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator and upload
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          VIDEO_PRIVACY: "unlisted"   # use "unlisted" while testing; switch to "public" later
        run: |
          python generate_and_upload_short.py

      - name: Commit updated riddles.xlsx (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add riddles.xlsx
            git commit -m "Mark riddle uploaded (automated)"
            git push
          else
            echo "No changes to commit"
          fi
